# encoding: UTF-8
# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 20140726183009) do

  create_table "players", force: true do |t|
    t.string   "name"
    t.string   "position"
    t.string   "team"
    t.string   "team_abbreviation"
    t.integer  "bye_week"
    t.integer  "rank"
    t.integer  "best_rank"
    t.integer  "worst_rank"
    t.float    "average_rank"
    t.float    "rank_standard_deviation"
    t.integer  "average_draft_position"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "projection_for_ks", force: true do |t|
    t.integer  "player_id"
    t.float    "field_goals_made"
    t.integer  "field_goals_made_high"
    t.integer  "field_goals_made_low"
    t.float    "field_goals_attempts"
    t.integer  "field_goals_attempts_high"
    t.integer  "field_goals_attempts_low"
    t.float    "extra_points"
    t.integer  "extra_points_high"
    t.integer  "extra_points_low"
    t.float    "fantasy_points"
    t.integer  "fantasy_points_high"
    t.integer  "fantasy_points_low"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "projection_for_ks", ["player_id"], name: "index_projection_for_ks_on_player_id"

  create_table "projection_for_qbs", force: true do |t|
    t.integer  "player_id"
    t.float    "pass_attempts"
    t.integer  "pass_attempts_high"
    t.integer  "pass_attempts_low"
    t.float    "pass_completions"
    t.integer  "pass_completions_high"
    t.integer  "pass_completions_low"
    t.float    "pass_yards"
    t.integer  "pass_yards_high"
    t.integer  "pass_yards_low"
    t.float    "pass_touchdowns"
    t.integer  "pass_touchdowns_high"
    t.integer  "pass_touchdowns_low"
    t.float    "pass_interceptions"
    t.integer  "pass_interceptions_high"
    t.integer  "pass_interceptions_low"
    t.float    "rush_attempts"
    t.integer  "rush_attempts_high"
    t.integer  "rush_attempts_low"
    t.float    "rush_yards"
    t.integer  "rush_yards_high"
    t.integer  "rush_yards_low"
    t.float    "rush_touchdowns"
    t.integer  "rush_touchdowns_high"
    t.integer  "rush_touchdowns_low"
    t.float    "fumbles"
    t.integer  "fumbles_high"
    t.integer  "fumbles_low"
    t.float    "fantasy_points"
    t.integer  "fantasy_points_high"
    t.integer  "fantasy_points_low"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "projection_for_qbs", ["player_id"], name: "index_projection_for_qbs_on_player_id"

  create_table "projection_for_rbs", force: true do |t|
    t.integer  "player_id"
    t.float    "rush_attempts"
    t.integer  "rush_attempts_high"
    t.integer  "rush_attempts_low"
    t.float    "rush_yards"
    t.integer  "rush_yards_high"
    t.integer  "rush_yards_low"
    t.float    "rush_touchdowns"
    t.integer  "rush_touchdowns_high"
    t.integer  "rush_touchdowns_low"
    t.float    "receiving_completions"
    t.integer  "receiving_completions_high"
    t.integer  "receiving_completions_low"
    t.float    "receiving_yards"
    t.integer  "receiving_yards_high"
    t.integer  "receiving_yards_low"
    t.float    "receiving_touchdowns"
    t.integer  "receiving_touchdowns_high"
    t.integer  "receiving_touchdowns_low"
    t.float    "fumbles"
    t.integer  "fumbles_high"
    t.integer  "fumbles_low"
    t.float    "fantasy_points"
    t.integer  "fantasy_points_high"
    t.integer  "fantasy_points_low"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "projection_for_rbs", ["player_id"], name: "index_projection_for_rbs_on_player_id"

  create_table "projection_for_tes", force: true do |t|
    t.integer  "player_id"
    t.float    "receiving_completions"
    t.integer  "receiving_completions_high"
    t.integer  "receiving_completions_low"
    t.float    "receiving_yards"
    t.integer  "receiving_yards_high"
    t.integer  "receiving_yards_low"
    t.float    "receiving_touchdowns"
    t.integer  "receiving_touchdowns_high"
    t.integer  "receiving_touchdowns_low"
    t.float    "fumbles"
    t.integer  "fumbles_high"
    t.integer  "fumbles_low"
    t.float    "fantasy_points"
    t.integer  "fantasy_points_high"
    t.integer  "fantasy_points_low"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "projection_for_tes", ["player_id"], name: "index_projection_for_tes_on_player_id"

  create_table "projection_for_wrs", force: true do |t|
    t.integer  "player_id"
    t.float    "rush_attempts"
    t.integer  "rush_attempts_high"
    t.integer  "rush_attempts_low"
    t.float    "rush_yards"
    t.integer  "rush_yards_high"
    t.integer  "rush_yards_low"
    t.float    "rush_touchdowns"
    t.integer  "rush_touchdowns_high"
    t.integer  "rush_touchdowns_low"
    t.float    "receiving_completions"
    t.integer  "receiving_completions_high"
    t.integer  "receiving_completions_low"
    t.float    "receiving_yards"
    t.integer  "receiving_yards_high"
    t.integer  "receiving_yards_low"
    t.float    "receiving_touchdowns"
    t.integer  "receiving_touchdowns_high"
    t.integer  "receiving_touchdowns_low"
    t.float    "fumbles"
    t.integer  "fumbles_high"
    t.integer  "fumbles_low"
    t.float    "fantasy_points"
    t.integer  "fantasy_points_high"
    t.integer  "fantasy_points_low"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "projection_for_wrs", ["player_id"], name: "index_projection_for_wrs_on_player_id"

  create_table "stat_for_ds", force: true do |t|
    t.integer  "player_id"
    t.integer  "games_played"
    t.float    "points_per_game"
    t.float    "yards_per_game"
    t.float    "rush_yards_per_game"
    t.float    "pass_yards_per_game"
    t.integer  "interceptions"
    t.integer  "interceptions_for_touchdowns"
    t.integer  "forced_fumbles"
    t.integer  "defense_touchdowns"
    t.integer  "tackles"
    t.integer  "pass_defended"
    t.integer  "sacks"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "stat_for_ds", ["player_id"], name: "index_stat_for_ds_on_player_id"

  create_table "stat_for_ks", force: true do |t|
    t.integer  "player_id"
    t.integer  "games_played"
    t.integer  "yards_0_to_19_made"
    t.integer  "yards_0_to_19_attempts"
    t.float    "yards_0_to_19_percent"
    t.integer  "yards_20_to_29_made"
    t.integer  "yards_20_to_29_attempts"
    t.float    "yards_20_to_29_percent"
    t.integer  "yards_30_to_39_made"
    t.integer  "yards_30_to_39_attempts"
    t.float    "yards_30_to_39_percent"
    t.integer  "yards_40_to_49_made"
    t.integer  "yards_40_to_49_attempts"
    t.float    "yards_40_to_49_percent"
    t.integer  "yards_50_made"
    t.integer  "yards_50_attempts"
    t.float    "yards_50_percent"
    t.integer  "field_goals_made"
    t.integer  "field_goals_attempts"
    t.float    "field_goals_percent"
    t.integer  "field_goals_long"
    t.integer  "extra_points"
    t.integer  "extra_points_attempts"
    t.float    "extra_points_percent"
    t.integer  "points"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "stat_for_ks", ["player_id"], name: "index_stat_for_ks_on_player_id"

  create_table "stat_for_qbs", force: true do |t|
    t.integer  "player_id"
    t.integer  "games_played"
    t.float    "qb_rating"
    t.integer  "pass_completions"
    t.integer  "pass_attempts"
    t.float    "pass_completion_percent"
    t.integer  "pass_yards"
    t.float    "pass_yards_per_game"
    t.float    "pass_yards_per_attempt"
    t.integer  "pass_touchdowns"
    t.integer  "pass_interceptions"
    t.integer  "rush_attempts"
    t.integer  "rush_yards"
    t.float    "rush_yards_per_game"
    t.float    "rush_average_yards_per_carry"
    t.integer  "rush_touchdowns"
    t.integer  "sacks"
    t.integer  "yards_lost"
    t.integer  "fumbles"
    t.integer  "fumbles_lost"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "stat_for_qbs", ["player_id"], name: "index_stat_for_qbs_on_player_id"

  create_table "stat_for_rbs", force: true do |t|
    t.integer  "player_id"
    t.integer  "games_played"
    t.integer  "rush_attempts"
    t.integer  "rush_yards"
    t.float    "rush_yards_per_game"
    t.float    "rush_average_yards_per_carry"
    t.integer  "rush_touchdowns"
    t.integer  "receiving_completions"
    t.integer  "receiving_target"
    t.integer  "receiving_yards"
    t.float    "receiving_yards_per_game"
    t.float    "receiving_average_yards_per_completion"
    t.integer  "receiving_long"
    t.float    "receiving_yards_after_catch"
    t.integer  "receiving_first_downs"
    t.integer  "receiving_touchdowns"
    t.integer  "fumbles"
    t.integer  "fumbles_lost"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "stat_for_rbs", ["player_id"], name: "index_stat_for_rbs_on_player_id"

  create_table "stat_for_tes", force: true do |t|
    t.integer  "player_id"
    t.integer  "games_played"
    t.integer  "receiving_completions"
    t.integer  "receiving_target"
    t.integer  "receiving_yards"
    t.float    "receiving_yards_per_game"
    t.float    "receiving_average_yards_per_completion"
    t.integer  "receiving_long"
    t.float    "receiving_yards_after_catch"
    t.integer  "receiving_first_downs"
    t.integer  "receiving_touchdowns"
    t.integer  "rush_attempts"
    t.integer  "rush_yards"
    t.float    "rush_yards_per_game"
    t.float    "rush_average_yards_per_carry"
    t.integer  "rush_touchdowns"
    t.integer  "fumbles"
    t.integer  "fumbles_lost"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "stat_for_tes", ["player_id"], name: "index_stat_for_tes_on_player_id"

  create_table "stat_for_wrs", force: true do |t|
    t.integer  "player_id"
    t.integer  "games_played"
    t.integer  "receiving_completions"
    t.integer  "receiving_target"
    t.integer  "receiving_yards"
    t.float    "receiving_yards_per_game"
    t.float    "receiving_average_yards_per_completion"
    t.integer  "receiving_long"
    t.float    "receiving_yards_after_catch"
    t.integer  "receiving_first_downs"
    t.integer  "receiving_touchdowns"
    t.integer  "kick_return_attempts"
    t.integer  "kick_return_yards"
    t.float    "kick_return_yards_per_attempt"
    t.integer  "kick_return_long"
    t.integer  "kick_return_touchdowns"
    t.integer  "punt_return_attempts"
    t.integer  "punt_return_yards"
    t.float    "punt_return_yards_per_attempt"
    t.integer  "punt_return_long"
    t.integer  "punt_return_touchdowns"
    t.integer  "fumbles"
    t.integer  "fumbles_lost"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "stat_for_wrs", ["player_id"], name: "index_stat_for_wrs_on_player_id"

  create_table "teams", force: true do |t|
    t.string   "team"
    t.string   "team_abbreviation"
    t.integer  "bye_week"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

end
